Name:           ros-jade-sicktoolbox
Version:        1.0.103
Release:        0%{?dist}
Summary:        ROS sicktoolbox package

Group:          Development/Libraries
License:        BSD
URL:            http://sicktoolbox.sourceforge.net/
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-jade-catkin

%description
SICK Toolbox drivers for SICK laser rangefinders This package contains the ROS
fork of the SICK LIDAR Matlab/C++ Toolbox, available from
http://sicktoolbox.sourceforge.net/. The SICK LIDAR Matlab/C++ Toolbox offers
stable and easy-to-use C++ drivers for SICK LMS 2xx and SICK LD LIDARs. Also
included are config utilities, examples, and tutorials.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed Apr 22 2015 Chad Rockey <chadrockey@gmail.com> - 1.0.103-0
- Autogenerated by Bloom

